### ISSUE TITLE
windows builds gone?

### ISSUE THREAD

**Issue by loriab** [conda-forge/dftd4-python-feedstock#24]
### Comment:

I couldn't see who/why the windows was removed from the build matrix upon the v3.5.0 update. Could they be reactivated, or is there technical trouble? Thanks!

**Comment by awvwgk** [comment]
I deactivated the Windows build after hitting more problems with GCC 5.3, patching was also not trivial like before.

**Comment by loriab** [comment]
ok, thanks. Intel compilers seem increasingly available, so I'll let you know if I spot a Win+Fortran+Intel recipe.

**Comment by awvwgk** [comment]
With the update of MinGW I could reenable the build for dftd3 on Windows already. For dftd4 I am stuck with linking Lapack, see https://github.com/conda-forge/dftd4-feedstock/pull/22. Any suggestions are welcome.
